site_name: Quattor Documentation

theme: 'readthedocs'

pages:
- introduction: 'index.md'
- components:
    - accounts: components/accounts.md
    - accounts::functions: components/accounts::functions.md
    - accounts::schema: components/accounts::schema.md
    - afsclt: components/afsclt.md
    - afsclt::schema: components/afsclt::schema.md
    - aii::freeipa::schema: components/aii::freeipa::schema.md
    - aii::opennebula::functions: components/aii::opennebula::functions.md
    - aii::opennebula::schema: components/aii::opennebula::schema.md
    - aiiserver: components/aiiserver.md
    - aiiserver::schema: components/aiiserver::schema.md
    - altlogrotate: components/altlogrotate.md
    - altlogrotate::schema: components/altlogrotate::schema.md
    - amandaserver: components/amandaserver.md
    - amandaserver::schema: components/amandaserver::schema.md
    - authconfig: components/authconfig.md
    - authconfig::schema: components/authconfig::schema.md
    - authconfig::sssd: components/authconfig::sssd.md
    - authconfig::sssd::ipa: components/authconfig::sssd::ipa.md
    - authconfig::sssd::ldap: components/authconfig::sssd::ldap.md
    - authconfig::sssd::sasl: components/authconfig::sssd::sasl.md
    - authconfig::sssd::sudo: components/authconfig::sssd::sudo.md
    - authconfig::sssd::tls: components/authconfig::sssd::tls.md
    - authconfig::sssd::user: components/authconfig::sssd::user.md
    - autofs: components/autofs.md
    - autofs::schema: components/autofs::schema.md
    - ccm: components/ccm.md
    - ccm::schema: components/ccm::schema.md
    - cdp: components/cdp.md
    - cdp::schema: components/cdp::schema.md
    - ceph: components/ceph.md
    - Ceph::commands: components/Ceph::commands.md
    - Ceph::compare: components/Ceph::compare.md
    - Ceph::config: components/Ceph::config.md
    - Ceph::crushmap: components/Ceph::crushmap.md
    - Ceph::daemon: components/Ceph::daemon.md
    - ceph::schema-mds: components/ceph::schema-mds.md
    - ceph::schema-mon: components/ceph::schema-mon.md
    - ceph::schema-osd: components/ceph::schema-osd.md
    - ceph::schema-rgw: components/ceph::schema-rgw.md
    - ceph::schema: components/ceph::schema.md
    - chkconfig: components/chkconfig.md
    - chkconfig::schema: components/chkconfig::schema.md
    - cron: components/cron.md
    - cron::schema: components/cron::schema.md
    - cups: components/cups.md
    - cups::schema: components/cups::schema.md
    - dirperm: components/dirperm.md
    - dirperm::schema: components/dirperm::schema.md
    - download: components/download.md
    - download::schema: components/download::schema.md
    - etcservices: components/etcservices.md
    - etcservices::schema: components/etcservices::schema.md
    - filecopy: components/filecopy.md
    - filecopy::schema: components/filecopy::schema.md
    - filesystems: components/filesystems.md
    - filesystems::schema: components/filesystems::schema.md
    - fmonagent: components/fmonagent.md
    - fmonagent::schema: components/fmonagent::schema.md
    - freeipa: components/freeipa.md
    - FreeIPA::Cert: components/FreeIPA::Cert.md
    - FreeIPA::CLI: components/FreeIPA::CLI.md
    - FreeIPA::Client: components/FreeIPA::Client.md
    - FreeIPA::DNS: components/FreeIPA::DNS.md
    - FreeIPA::Group: components/FreeIPA::Group.md
    - FreeIPA::Host: components/FreeIPA::Host.md
    - FreeIPA::Logger: components/FreeIPA::Logger.md
    - FreeIPA::NSS: components/FreeIPA::NSS.md
    - freeipa::schema: components/freeipa::schema.md
    - FreeIPA::Service: components/FreeIPA::Service.md
    - FreeIPA::User: components/FreeIPA::User.md
    - fstab: components/fstab.md
    - fstab::schema: components/fstab::schema.md
    - ganglia: components/ganglia.md
    - ganglia::schema: components/ganglia::schema.md
    - gmetad: components/gmetad.md
    - gmetad::schema: components/gmetad::schema.md
    - gmond: components/gmond.md
    - gmond::schema: components/gmond::schema.md
    - gpfs: components/gpfs.md
    - gpfs::schema: components/gpfs::schema.md
    - grub: components/grub.md
    - grub::schema: components/grub::schema.md
    - hostsaccess: components/hostsaccess.md
    - hostsaccess::schema: components/hostsaccess::schema.md
    - hostsfile: components/hostsfile.md
    - hostsfile::schema: components/hostsfile::schema.md
    - icinga: components/icinga.md
    - icinga::functions: components/icinga::functions.md
    - icinga::schema: components/icinga::schema.md
    - interactivelimits: components/interactivelimits.md
    - interactivelimits::schema: components/interactivelimits::schema.md
    - ipmi: components/ipmi.md
    - ipmi::schema: components/ipmi::schema.md
    - iptables: components/iptables.md
    - iptables::schema: components/iptables::schema.md
    - ldconf: components/ldconf.md
    - ldconf::schema: components/ldconf::schema.md
    - libvirtd: components/libvirtd.md
    - libvirtd::schema: components/libvirtd::schema.md
    - metaconfig: components/metaconfig.md
    - metaconfig::schema: components/metaconfig::schema.md
    - modprobe: components/modprobe.md
    - modprobe::schema: components/modprobe::schema.md
    - mysql: components/mysql.md
    - mysql::schema: components/mysql::schema.md
    - nagios: components/nagios.md
    - nagios::functions: components/nagios::functions.md
    - nagios::schema: components/nagios::schema.md
    - named: components/named.md
    - named::schema: components/named::schema.md
    - network: components/network.md
    - network::core-schema: components/network::core-schema.md
    - network::schema: components/network::schema.md
    - nfs: components/nfs.md
    - nfs::schema: components/nfs::schema.md
    - nrpe: components/nrpe.md
    - nrpe::schema: components/nrpe::schema.md
    - nsca: components/nsca.md
    - nsca::schema: components/nsca::schema.md
    - nscd: components/nscd.md
    - nscd::schema: components/nscd::schema.md
    - nss: components/nss.md
    - nss::schema: components/nss::schema.md
    - ntpd: components/ntpd.md
    - ntpd::schema: components/ntpd::schema.md
    - ofed: components/ofed.md
    - ofed::schema: components/ofed::schema.md
    - openldap: components/openldap.md
    - openldap::schema: components/openldap::schema.md
    - opennebula: components/opennebula.md
    - OpenNebula::Account: components/OpenNebula::Account.md
    - OpenNebula::AII: components/OpenNebula::AII.md
    - OpenNebula::Ceph: components/OpenNebula::Ceph.md
    - OpenNebula::Commands: components/OpenNebula::Commands.md
    - OpenNebula::Host: components/OpenNebula::Host.md
    - OpenNebula::Image: components/OpenNebula::Image.md
    - OpenNebula::Network: components/OpenNebula::Network.md
    - opennebula::schema: components/opennebula::schema.md
    - OpenNebula::Server: components/OpenNebula::Server.md
    - OpenNebula::VM: components/OpenNebula::VM.md
    - openvpn: components/openvpn.md
    - openvpn::schema: components/openvpn::schema.md
    - pam: components/pam.md
    - pam::config: components/pam::config.md
    - pam::schema: components/pam::schema.md
    - path: components/path.md
    - path::schema: components/path::schema.md
    - pnp4nagios: components/pnp4nagios.md
    - pnp4nagios::schema: components/pnp4nagios::schema.md
    - postfix: components/postfix.md
    - postfix::schema: components/postfix::schema.md
    - postgresql: components/postgresql.md
    - postgresql::schema: components/postgresql::schema.md
    - profile: components/profile.md
    - profile::functions: components/profile::functions.md
    - profile::schema: components/profile::schema.md
    - puppet: components/puppet.md
    - puppet::schema: components/puppet::schema.md
    - resolver: components/resolver.md
    - resolver::schema: components/resolver::schema.md
    - sendmail: components/sendmail.md
    - sendmail::schema: components/sendmail::schema.md
    - shorewall::schema: components/shorewall::schema.md
    - spma-run: components/spma-run.md
    - spma: components/spma.md
    - spma::apt: components/spma::apt.md
    - spma::apt::schema: components/spma::apt::schema.md
    - spma::functions: components/spma::functions.md
    - spma::ips: components/spma::ips.md
    - spma::ips::schema: components/spma::ips::schema.md
    - spma::schema-common-yum: components/spma::schema-common-yum.md
    - spma::schema: components/spma::schema.md
    - spma::software: components/spma::software.md
    - spma::yum: components/spma::yum.md
    - spma::yum::schema: components/spma::yum::schema.md
    - spma::yumng: components/spma::yumng.md
    - spma::yumng::schema: components/spma::yumng::schema.md
    - ssh: components/ssh.md
    - ssh::schema: components/ssh::schema.md
    - sudo: components/sudo.md
    - sudo::functions: components/sudo::functions.md
    - sudo::schema: components/sudo::schema.md
    - symlink: components/symlink.md
    - symlink::schema: components/symlink::schema.md
    - sysconfig: components/sysconfig.md
    - sysconfig::schema: components/sysconfig::schema.md
    - sysctl: components/sysctl.md
    - sysctl::schema: components/sysctl::schema.md
    - syslog: components/syslog.md
    - syslog::schema: components/syslog::schema.md
    - syslogng: components/syslogng.md
    - syslogng::schema: components/syslogng::schema.md
    - systemd: components/systemd.md
    - systemd::functions: components/systemd::functions.md
    - systemd::schema: components/systemd::schema.md
    - Systemd::Service: components/Systemd::Service.md
    - Systemd::Service::Chkconfig: components/Systemd::Service::Chkconfig.md
    - Systemd::Service::Component::chkconfig: components/Systemd::Service::Component::chkconfig.md
    - Systemd::Service::Unit: components/Systemd::Service::Unit.md
    - Systemd::Systemctl: components/Systemd::Systemctl.md
    - Systemd::UnitFile: components/Systemd::UnitFile.md
    - useraccess: components/useraccess.md
    - useraccess::schema: components/useraccess::schema.md
- CAF:
    - Application: CAF/Application.md
    - Download::LWP: CAF/Download::LWP.md
    - FileEditor: CAF/FileEditor.md
    - FileReader: CAF/FileReader.md
    - FileWriter: CAF/FileWriter.md
    - History: CAF/History.md
    - Kerberos: CAF/Kerberos.md
    - Lock: CAF/Lock.md
    - Log: CAF/Log.md
    - Object: CAF/Object.md
    - ObjectText: CAF/ObjectText.md
    - Path: CAF/Path.md
    - Process: CAF/Process.md
    - Reporter: CAF/Reporter.md
    - ReporterMany: CAF/ReporterMany.md
    - RuleBasedEditor: CAF/RuleBasedEditor.md
    - Service: CAF/Service.md
    - TextRender: CAF/TextRender.md
- CCM:
    - CacheManager: CCM/CacheManager.md
    - CacheManager::Configuration: CCM/CacheManager::Configuration.md
    - CacheManager::DB: CCM/CacheManager::DB.md
    - CacheManager::Element: CCM/CacheManager::Element.md
    - CacheManager::Encode: CCM/CacheManager::Encode.md
    - CacheManager::Resource: CCM/CacheManager::Resource.md
    - CCfg: CCM/CCfg.md
    - CLI: CCM/CLI.md
    - Fetch: CCM/Fetch.md
    - Fetch::Config: CCM/Fetch::Config.md
    - Fetch::Download: CCM/Fetch::Download.md
    - Fetch::JSONProfileSimple: CCM/Fetch::JSONProfileSimple.md
    - Fetch::JSONProfileTyped: CCM/Fetch::JSONProfileTyped.md
    - Fetch::ProfileCache: CCM/Fetch::ProfileCache.md
    - Fetch::XMLPanProfile: CCM/Fetch::XMLPanProfile.md
    - Options: CCM/Options.md
    - Path: CCM/Path.md
    - TextRender: CCM/TextRender.md
    - TextRender::Scalar: CCM/TextRender::Scalar.md
- components-grid:
    - condorconfig: components-grid/condorconfig.md
    - condorconfig::schema: components-grid/condorconfig::schema.md
    - dcache: components-grid/dcache.md
    - dcache::schema: components-grid/dcache::schema.md
    - dpmlfc: components-grid/dpmlfc.md
    - dpmlfc::schema: components-grid/dpmlfc::schema.md
    - gacl: components-grid/gacl.md
    - gacl::schema: components-grid/gacl::schema.md
    - gip2: components-grid/gip2.md
    - gip2::schema: components-grid/gip2::schema.md
    - glitestartup: components-grid/glitestartup.md
    - glitestartup::functions: components-grid/glitestartup::functions.md
    - glitestartup::schema: components-grid/glitestartup::schema.md
    - globuscfg: components-grid/globuscfg.md
    - globuscfg::schema: components-grid/globuscfg::schema.md
    - gridmapdir: components-grid/gridmapdir.md
    - gridmapdir::schema: components-grid/gridmapdir::schema.md
    - gsissh: components-grid/gsissh.md
    - gsissh::schema: components-grid/gsissh::schema.md
    - lbconfig: components-grid/lbconfig.md
    - lbconfig::schema: components-grid/lbconfig::schema.md
    - lcas: components-grid/lcas.md
    - lcas::schema: components-grid/lcas::schema.md
    - lcgbdii: components-grid/lcgbdii.md
    - lcgbdii::schema: components-grid/lcgbdii::schema.md
    - lcgmonjob: components-grid/lcgmonjob.md
    - lcgmonjob::schema: components-grid/lcgmonjob::schema.md
    - lcmaps: components-grid/lcmaps.md
    - lcmaps::schema: components-grid/lcmaps::schema.md
    - maui: components-grid/maui.md
    - maui::schema: components-grid/maui::schema.md
    - mkgridmap: components-grid/mkgridmap.md
    - mkgridmap::schema: components-grid/mkgridmap::schema.md
    - myproxy: components-grid/myproxy.md
    - myproxy::schema: components-grid/myproxy::schema.md
    - pbsclient: components-grid/pbsclient.md
    - pbsclient::schema: components-grid/pbsclient::schema.md
    - pbsknownhosts: components-grid/pbsknownhosts.md
    - pbsknownhosts::schema: components-grid/pbsknownhosts::schema.md
    - pbsserver: components-grid/pbsserver.md
    - pbsserver::schema: components-grid/pbsserver::schema.md
    - vomsclient: components-grid/vomsclient.md
    - vomsclient::schema: components-grid/vomsclient::schema.md
    - wlconfig: components-grid/wlconfig.md
    - wlconfig::schema: components-grid/wlconfig::schema.md
    - wmsclient: components-grid/wmsclient.md
    - wmsclient::schema: components-grid/wmsclient::schema.md
    - wmslb: components-grid/wmslb.md
    - wmslb::schema: components-grid/wmslb::schema.md
    - xrootd: components-grid/xrootd.md
    - xrootd::schema: components-grid/xrootd::schema.md
- Unittesting:
    - Quattor: Unittesting/Quattor.md
    - Quattor::CommonDeps: Unittesting/Quattor::CommonDeps.md
    - Quattor::Component: Unittesting/Quattor::Component.md
    - Quattor::Critic: Unittesting/Quattor::Critic.md
    - Quattor::Doc: Unittesting/Quattor::Doc.md
    - Quattor::Filetools: Unittesting/Quattor::Filetools.md
    - Quattor::Namespace: Unittesting/Quattor::Namespace.md
    - Quattor::Object: Unittesting/Quattor::Object.md
    - Quattor::Panc: Unittesting/Quattor::Panc.md
    - Quattor::ProfileCache: Unittesting/Quattor::ProfileCache.md
    - Quattor::RegexpTest: Unittesting/Quattor::RegexpTest.md
    - Quattor::TextRender: Unittesting/Quattor::TextRender.md
    - Quattor::TextRender::Base: Unittesting/Quattor::TextRender::Base.md
    - Quattor::TextRender::Component: Unittesting/Quattor::TextRender::Component.md
    - Quattor::TextRender::Metaconfig: Unittesting/Quattor::TextRender::Metaconfig.md
    - Quattor::TextRender::RegexpTest: Unittesting/Quattor::TextRender::RegexpTest.md
    - Quattor::TextRender::Suite: Unittesting/Quattor::TextRender::Suite.md
    - Quattor::Tidy: Unittesting/Quattor::Tidy.md
    - Quattor::Unittest: Unittesting/Quattor::Unittest.md
